### ISSUE TITLE
Nearby stars LC report - selected stars not quite nearby

### ISSUE THREAD

**Issue by orionlee** [noraeisner/LATTE#11]
It appears that the selected stars are not quite nearby, at least in the few I have spot checked.

Example, for [TIC 308300731](https://exofop.ipac.caltech.edu/tess/target.php?id=308300731), see the following is an excerpt of the nearby stars LC report below [*].
1. The stars listed in the report are not found in the [ExoFOP's nearby star list](https://exofop.ipac.caltech.edu/tess/nearbytarget.php?id=308300731)
2. I spot checked the closest 2 in the report, using the co-ordinates supplied by ExoFOP. The two (TIC 308360391 and TIC 308299799) are quite far away: 500+ arcseconds.

Assuming the co-ordinates provided by ExoFOP are accurate, it appears LATTE's selection has some issues.

---
[*] Excerpt of the nearby stars LC report:

![image](https://user-images.githubusercontent.com/250644/92508464-87f03200-f1bd-11ea-9c7f-9c1a7f073d44.png)

**Comment by noraeisner** [comment]
Hi, thanks for pointing this out. The mistake was in the units of the figure - the distance quoted there is in arcminutes and not arcseconds. As this figure only shows the nearest stars that were observed in the two-minute cadence data (and not the FFIs), these distances are often quite large. The unit error has been corrected for the new release.

**Comment by orionlee** [comment]
@noraeisner The unit error remained in `LATTE-dev` branch as of commit 94e4ddfe074bd42f3021b1c78f1801a65674bffd . Just a reminder in case the fix got lost.
